[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
which = "5.0.0"
colored = "2.0"
walkdir = "2.3.2"
fs_extra = "1.2.0"
sys-info = "0.9.1"
sysinfo = "0.14.0"